import { HttpClient } from "@angular/common/http" // Changed from 'import type'
import {map, Observable} from "rxjs" // Changed from 'import type'
import { environment } from "../../environments/environment"
import { Injectable } from "@angular/core"

export interface Mocktail {
  id: number
  name: string
  description: string
  price: number
  available: boolean
  image: string
  ingredients: Array<{
    name: string
    quantity: number
    unit: string
    allergen: string // Champ allergène obligatoire
  }>
}

export interface Ingredient {
  stockStatus:string;
  id: number
  name: string
  quantity: number
  restock_threshold: number
  unit: string
}

export interface CreateMocktailRequest {
  name: string
  description: string
  price: number
  image: string
  ingredients: Array<{
    id?: number // Optional 'id' for creation, as it might be generated by backend
    name: string
    quantity: number
    unit: string
  }>
}

export interface UpdateMocktailRequest {
  name: string
  description: string
  price: number
  image: string
  ingredients: Array<{
    id?: number // Optional 'id' for update, as it might be generated by backend
    name: string
    quantity: number
    unit: string
  }>
}

@Injectable({
  providedIn: "root",
})
export class MocktailService {
  private apiUrl = environment.apiUrl

  constructor(private http: HttpClient) {}

  getAll(): Observable<Mocktail[]> {
    return this.http.get<Mocktail[]>(`${environment.apiUrl}/MocktailQuery/getAllMocktails`);
  }
  getById(id: number): Observable<Mocktail> {
    return this.http.get<Mocktail>(`${this.apiUrl}/${id}`);
  }

  create(mocktail: CreateMocktailRequest): Observable<Mocktail> {
    return this.http.post<Mocktail>(`${environment.apiUrl}/MocktailCommand/CreateMocktail`, mocktail);
  }


  update(id: number, mocktail: UpdateMocktailRequest): Observable<Mocktail> {
    return this.http.put<Mocktail>(`${environment.apiUrl}/MocktailCommand/UpdateMocktail/${id}`, mocktail);
  }


  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${environment.apiUrl}/MocktailCommand/DeleteMocktail/${id}`);
  }


  // Nouvelle méthode pour récupérer tous les ingrédients
  getAllIngredients(): Observable<Ingredient[]> {
    return this.http.get<{ ingredients: Ingredient[] }>(`${environment.ingredientApiUrl}/getAllIngredients`)
      .pipe(
        map(response => response.ingredients)
      );
  }


}
